Algoritmo "circulação de carros"

Var
placa: inteiro


Inicio

escreva ("Por favor nos informe o último número da placa do seu carro: ")
leia (placa)

escolha placa
caso 0,1,2
escreva ("Não circular na segunda-feira")
caso 3, 4
escreva ("Não circular na terça-feira")
caso 5, 6
escreva ("Não circular na quarta-feira")
caso 7, 8
escreva ("Não circular na quinta-feira")
caso 9
escreva ("Não circular na sexta-feira")
fimescolha

Fimalgoritmo